# Generated by Django 5.1.4 on 2024-12-10 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_birthday_remove_user_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_absent", models.BooleanField()),
                ("date", models.DateField(auto_now_add=True)),
                ("deserved_time", models.IntegerField(editable=False, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_accepted", models.BooleanField(default=False, editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salaire_de_base",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "salaire_partie_fixe",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "partie_variable",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "iep",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Indemnité d'expérience professionnelle",
                    ),
                ),
                (
                    "indemnite_travail_poste",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ifsp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Indemnité forfaitaire service permanent",
                    ),
                ),
                (
                    "indemnite_de_nuisance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "indemnite_travail_de_nuit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "indemnite_interim",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Indemnité d'intérim (rempl.)",
                    ),
                ),
                (
                    "prime_de_permanence",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "indemnite_d_astreinte",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "heures_supplementaires",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "indemnite_de_conge_annuel",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_d_inventaire",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_de_bilan",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "pri",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="PRI (Prime de rendement individuel)",
                    ),
                ),
                (
                    "prc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="PRC (Prime de rendement collectif)",
                    ),
                ),
                (
                    "prime_encouragement_annuelle",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_de_benefice_annuelle",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_d_innovation",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "panier",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transport",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "telephone",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "iuvp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="I.U.V.P (Indemnité utilisation véhicule privé)",
                    ),
                ),
                (
                    "prime_exceptionnelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Prime exceptionnelle (Aïd, etc.)",
                    ),
                ),
                (
                    "allocation_fin_carriere",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "allocation_de_deces",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "allocations_familiales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_de_scolarite",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "salaire_unique",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "frais_de_missions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prime_de_zone",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "indemnite_de_licenciement",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bonification_enfants_de_chouhadas",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
