# Generated by Django 5.1.4 on 2024-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_absence_leave_notificationabsence_payroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="0000000000", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="worker", max_length=32),
            preserve_default=False,
        ),
    ]
