# Generated by Django 5.1.4 on 2024-12-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_leave_reason_user_companyname_user_leave_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="is_accepted",
        ),
        migrations.AddField(
            model_name="leave",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="leave_files"),
        ),
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="payslips")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
