# Generated by Django 5.1.4 on 2024-12-10 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_leave_is_accepted_leave_file_leave_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absence",
            name="is_absent",
        ),
        migrations.AddField(
            model_name="absence",
            name="check_in",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="absence",
            name="check_out",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="absence",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
