# Generated by Django 5.1.4 on 2024-12-10 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_absence_is_absent_absence_check_in_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absence",
            old_name="user_profile",
            new_name="user",
        ),
    ]
