# Generated by Django 5.1.4 on 2024-12-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_user_profile_absence_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_security_social",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 10, 9, 42, 25, 191962), max_length=9
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="worker", max_length=32),
        ),
    ]
