# Generated by Django 5.1.4 on 2024-12-10 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_social_security_social_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="social_security_social",
            new_name="social_security_number",
        ),
    ]
