# Generated by Django 5.1.4 on 2024-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_social_security_social_user_social_security_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="companyName",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
