# Generated by Django 5.1.4 on 2024-12-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_companyname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="min_number_worker",
            field=models.IntegerField(default=0),
        ),
    ]
