# Generated by Django 5.1.4 on 2024-12-11 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_min_number_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="salaire_de_base",
        ),
        migrations.AddField(
            model_name="user",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(default="worker", max_length=128),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=128)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NotificationAbsence",
        ),
    ]
