# Generated by Django 5.1.4 on 2024-12-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_payroll_salaire_de_base_user_base_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=128)),
                (
                    "fixed_salary_part",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "variable_part",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("iep", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "shift_work_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("ifsp", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "disruption_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "night_work_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "interim_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "standby_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "on_call_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("overtime", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "annual_leave_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "inventory_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "end_of_year_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("pri", models.FloatField(blank=True, default=0.0, null=True)),
                ("prc", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "annual_encouragement_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "annual_profit_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "innovation_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "meal_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("transport", models.FloatField(blank=True, default=0.0, null=True)),
                ("phone", models.FloatField(blank=True, default=0.0, null=True)),
                ("iuvp", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "exceptional_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "career_retirement_end_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "death_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "family_allowances",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("school_bonus", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "unique_salary",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "mission_expenses",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("zone_bonus", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "dismissal_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "children_of_martyrs_bonus",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="company",
            field=models.CharField(default="ibm", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contracts"),
        ),
        migrations.DeleteModel(
            name="Payroll",
        ),
    ]
